### ISSUE TITLE
Write contribution guidelines for our GD399-* repos

### ISSUE THREAD

**Issue by bjornmeansbear** [GD399-OSD/resources-readings#9]
Advise on how best to fork, add, then pull request. As well as how to briefly explain what you are adding/changing to make it more useful and meaningful.

**Comment by devinhalladay** [comment]
I can take this on! I'll submit a PR later so others can review.

**Comment by devinhalladay** [comment]
I'm closing this issue. I moved it into the new [GD399-Meta](https://github.com/GD399-OSD/GD399-Meta) repo to keep this repository on-topic.
